name: Tests

on:
  push:
    branches:
      - main

jobs:
  forge-tests:
    name: Forge Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Install Rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: "Clone Foundry repository"
        run: |
          if [ ! -d "foundry" ]; then
            git clone https://github.com/BuildBearLabs/foundry.git -b feat/single_json_output_new
          fi
        shell: bash

      - name: "Set Foundry commit hash"
        id: foundry_hash
        run: echo "hash=$(git -C foundry rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: "Restore Foundry build cache"
        uses: actions/cache@v3
        id: cache-foundry
        with:
          path: |
            foundry/target
            $HOME/.config/.foundry/bin
          key: ${{ runner.os }}-foundry-build-${{ steps.foundry_hash.outputs.hash }}

      - name: "Build Foundry from source or copy from target"
        run: |
          FOUNDRY_BIN="$HOME/.config/.foundry/bin/forge"
          TARGET_FORGE="foundry/target/release/forge"

          mkdir -p "$(dirname "$FOUNDRY_BIN")"

          if [ -f "$FOUNDRY_BIN" ]; then
            echo "✅ Forge binary found in bin path, skipping build."
          elif [ -f "$TARGET_FORGE" ]; then
            echo "✅ Forge binary found in target/release, copying to bin."
            cp "$TARGET_FORGE" "$FOUNDRY_BIN"
          else
            echo "❌ Forge binary not found, building from source..."
            cd foundry
            cargo b -r --bin forge
            cp target/release/forge "$FOUNDRY_BIN"
          fi

          echo "$(dirname "$FOUNDRY_BIN")" >> $GITHUB_PATH

      - name: "Save Foundry build cache"
        if: steps.cache-foundry.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            foundry/target
            $HOME/.config/.foundry/bin
          key: ${{ runner.os }}-foundry-build-${{ steps.foundry_hash.outputs.hash }}

      - name: "Show Forge version"
        run: forge --version

      - name: Build
        run: forge build
        env:
          FOUNDRY_PROFILE: ci

      - name: Run tests
        run: forge test --isolate -vvv
        continue-on-error: true
        env:
          FOUNDRY_PROFILE: ci
          FORGE_SNAPSHOT_CHECK: true

      - name: "Add summary"
        run: |
          echo "## Result for ${{ env.JOB_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "BB CI Run"
        uses: BuildBearLabs/buildbear_x_action@v1.7.3
        with:
          buildbear-api-key: "${{ secrets.BUILDBEAR_API_KEY }}"
